[package]
name = "mariochao/pie-hiking-plugin"
description = "Plugin kit with everything you need to pie hike."

version = "0.0.0"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/MarioChao/pie-hiking-plugin"

private = true

[dependencies]
ContainerMechanic = "mariochao/container-mechanic@0.2.0"
PriorityZoneGroup = "mariochao/priority-zone-group@1.0.0"
ScopedCollection = "mariochao/scoped-collection@1.0.0"
UIUtil = "mariochao/ui-util@0.0.1"
ZiplineTransportationSystem = "mariochao/zipline-transportation-system@0.7.1"
